-- seed_reading_long_fill_1kyu_50.sql
-- 英検1級 長文の語句空所補充 51問（17パッセージ×3空所）
-- 過去問形式: 約350語の説明文・評論文、各3空所・4肢選択。述部・接続表現・概念定義など。
-- 参照: docs/1級_長文空所_調査メモ.md、添付過去問6枚
-- 028 以降のマイグレーション実行後に実行

-- ========== 1: The Psychology of Nostalgia (過去問風) ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'The Psychology of Nostalgia\n\nIn the late seventeenth century, a physician observed that soldiers far from home often suffered from a condition we would now associate with intense longing for their native land. He attributed this to psychological rather than purely physical causes. Not everyone at the time accepted that __BLANK__. Some argued instead that climate or diet was to blame, and others proposed that certain sounds or sights triggered the affliction.\n\nBy the early nineteenth century, the term "nostalgia" had come to denote a form of melancholy or depression. Later, scholars such as Fred Davis argued that nostalgia in modern usage carries positive associations—fond memories of the past, childhood, or "the good old days"—unlike the suffering of those uprooted soldiers. __BLANK__ is now widely accepted: nostalgia as a bittersweet emotion is distinct from simple homesickness as a debilitating condition.\n\nRecent research suggests that nostalgia __BLANK__. Studies indicate that although nostalgic feelings are sometimes triggered by sadness or loss, they often involve reframing difficult experiences in a positive light. Strong nostalgic experiences have been correlated with greater happiness, higher self-esteem, and a reduced fear of mortality. Psychologists increasingly view nostalgia as a psychological resource rather than a weakness.',
  'The Psychology of Nostalgia',
  E'The Psychology of Nostalgia\n\nIn the late seventeenth century, a physician observed that soldiers far from home often suffered from a condition we would now associate with intense longing for their native land. He attributed this to psychological rather than purely physical causes. Not everyone at the time accepted that __BLANK__. Some argued instead that climate or diet was to blame, and others proposed that certain sounds or sights triggered the affliction.\n\nBy the early nineteenth century, the term "nostalgia" had come to denote a form of melancholy or depression. Later, scholars such as Fred Davis argued that nostalgia in modern usage carries positive associations—fond memories of the past, childhood, or "the good old days"—unlike the suffering of those uprooted soldiers. __BLANK__ is now widely accepted: nostalgia as a bittersweet emotion is distinct from simple homesickness as a debilitating condition.\n\nRecent research suggests that nostalgia __BLANK__. Studies indicate that although nostalgic feelings are sometimes triggered by sadness or loss, they often involve reframing difficult experiences in a positive light. Strong nostalgic experiences have been correlated with greater happiness, higher self-esteem, and a reduced fear of mortality. Psychologists increasingly view nostalgia as a psychological resource rather than a weakness.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["its cause was emotional in nature", "the symptoms were serious", "it could be effectively treated", "its sufferers were being honest"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["The distinction between the two concepts", "The need for more research", "The danger of romanticizing the past", "The role of memory in identity"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["can improve psychological well-being", "affects some people more strongly than others", "can be harmful if not properly managed", "often occurs without people realizing it"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 2: Invasive Species and Ecosystems (過去問風) ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'Invasive Species and Ecosystems\n\nCertain ant species have become formidable invaders when introduced to new continents. In their native range, periodic flooding forces them to abandon their nests and compete fiercely with other ants for territory. __BLANK__ shaped their evolution: over time they became highly aggressive and territorial, traits that served them well when they were later transported by human activity to regions where they had no natural competitors.\n\nThese ants rarely breed with other species and often eliminate rival colonies. Their genetic uniformity is an advantage in one respect: they recognize members of their own group easily and avoid wasteful conflict among themselves. This allows them to __BLANK__, forming vast supercolonies that overwhelm native ant populations. To casual observers they may seem harmless—small and without a painful sting—but their numbers and coordination make them devastating to local fauna.\n\nTheir impact extends beyond direct competition. __BLANK__: in some regions, predators that once fed on the larger native ants now refuse to eat the invaders, leading to declines in those predator populations. In other areas, the invaders have displaced native ants that played a crucial role in dispersing seeds, without fulfilling that ecological function themselves. The full consequences of such invasions are still being studied.',
  'Invasive Species and Ecosystems',
  E'Invasive Species and Ecosystems\n\nCertain ant species have become formidable invaders when introduced to new continents. In their native range, periodic flooding forces them to abandon their nests and compete fiercely with other ants for territory. __BLANK__ shaped their evolution: over time they became highly aggressive and territorial, traits that served them well when they were later transported by human activity to regions where they had no natural competitors.\n\nThese ants rarely breed with other species and often eliminate rival colonies. Their genetic uniformity is an advantage in one respect: they recognize members of their own group easily and avoid wasteful conflict among themselves. This allows them to __BLANK__, forming vast supercolonies that overwhelm native ant populations. To casual observers they may seem harmless—small and without a painful sting—but their numbers and coordination make them devastating to local fauna.\n\nTheir impact extends beyond direct competition. __BLANK__: in some regions, predators that once fed on the larger native ants now refuse to eat the invaders, leading to declines in those predator populations. In other areas, the invaders have displaced native ants that played a crucial role in dispersing seeds, without fulfilling that ecological function themselves. The full consequences of such invasions are still being studied.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["This state of constant struggle", "The presence of natural barriers", "A shortage of resources", "A type of extreme isolation"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["have higher population densities", "evolve more quickly", "migrate more frequently", "rely on fewer resources"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["They can also have indirect effects", "They can enhance local ecosystems", "They tend to attract harmful pests", "They sometimes fail to adapt well"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 3: Authenticating Art (過去問風) ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'Authenticating Art\n\nSome artists are known for recurring motifs—melting forms, dreamlike landscapes, or themes of decay and transformation. At times a painter may __BLANK__: curators examining one such work with advanced imaging discovered a hidden portrait beneath the visible surface, suggesting the artist had reused the canvas or reworked an earlier idea. Such findings remind us that the creation of art is often a process of layers and revisions.\n\nWhen a museum prepared an exhibition, it wished to include a particular painting attributed to this artist. The curators noticed, however, that the work differed from his known style of that period—sparser composition, different brushwork, and none of his characteristic motifs. They could not trace its ownership with certainty. __BLANK__. Was the painting really by the master, or had it been misattributed?\n\nA breakthrough came when staff found a photograph of a pavilion the artist had designed for a world fair. The painting in question turned out to be one panel of a larger mural that had been dismantled. __BLANK__: the work had been separated from its original context and its provenance had been lost. The museum reclassified and redated the painting accordingly, and researchers continue to investigate how and why it was detached from the larger piece.',
  'Authenticating Art',
  E'Authenticating Art\n\nSome artists are known for recurring motifs—melting forms, dreamlike landscapes, or themes of decay and transformation. At times a painter may __BLANK__: curators examining one such work with advanced imaging discovered a hidden portrait beneath the visible surface, suggesting the artist had reused the canvas or reworked an earlier idea. Such findings remind us that the creation of art is often a process of layers and revisions.\n\nWhen a museum prepared an exhibition, it wished to include a particular painting attributed to this artist. The curators noticed, however, that the work differed from his known style of that period—sparser composition, different brushwork, and none of his characteristic motifs. They could not trace its ownership with certainty. __BLANK__. Was the painting really by the master, or had it been misattributed?\n\nA breakthrough came when staff found a photograph of a pavilion the artist had designed for a world fair. The painting in question turned out to be one panel of a larger mural that had been dismantled. __BLANK__: the work had been separated from its original context and its provenance had been lost. The museum reclassified and redated the painting accordingly, and researchers continue to investigate how and why it was detached from the larger piece.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["even go a step further", "make the symbolism immediately obvious", "present the viewer with something familiar", "use images from his own dreams"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["They began to question the painting''s authenticity", "They decided to restore the painting", "They replaced it with a different work", "They sought to understand its symbolism"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["The museum had identified the work incorrectly", "The museum had an exact copy", "The artist had given the work to the museum", "The artist had never intended it to be seen"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 4: Two Approaches to History (過去問風) ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'Two Approaches to History\n\nOne ancient historian is often called the father of history. His great work drew on travels, oral accounts, and a willingness to weigh conflicting versions and highlight inconsistencies. He examined mythological elements with an unprecedented level of skepticism for his time. What sets his masterpiece apart from earlier chronicles is his __BLANK__: he did not simply record what he was told but scrutinized sources for plausibility and bias.\n\nAnother historian, his younger contemporary, wrote a detailed account of a long war between rival powers. His writing __BLANK__: he concentrated almost entirely on political and military events, with little of the cultural or ethnographic scope of his predecessor. His pragmatic analysis of statecraft and the rise and fall of empires influenced later thinkers from antiquity through the Renaissance and beyond. Statesmen and philosophers alike drew on his work to understand how power operates.\n\nThose influenced by the second historian __BLANK__. They looked to the past not for entertainment or broad narrative but for lessons applicable to their own times. In recent decades, however, the first historian has enjoyed a revival: his willingness to include diverse perspectives and social history, once dismissed by some as irrelevant, is now seen as essential to a rich and multifaceted understanding of the past.',
  'Two Approaches to History',
  E'Two Approaches to History\n\nOne ancient historian is often called the father of history. His great work drew on travels, oral accounts, and a willingness to weigh conflicting versions and highlight inconsistencies. He examined mythological elements with an unprecedented level of skepticism for his time. What sets his masterpiece apart from earlier chronicles is his __BLANK__: he did not simply record what he was told but scrutinized sources for plausibility and bias.\n\nAnother historian, his younger contemporary, wrote a detailed account of a long war between rival powers. His writing __BLANK__: he concentrated almost entirely on political and military events, with little of the cultural or ethnographic scope of his predecessor. His pragmatic analysis of statecraft and the rise and fall of empires influenced later thinkers from antiquity through the Renaissance and beyond. Statesmen and philosophers alike drew on his work to understand how power operates.\n\nThose influenced by the second historian __BLANK__. They looked to the past not for entertainment or broad narrative but for lessons applicable to their own times. In recent decades, however, the first historian has enjoyed a revival: his willingness to include diverse perspectives and social history, once dismissed by some as irrelevant, is now seen as essential to a rich and multifaceted understanding of the past.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["critical approach toward his sources", "reliance on written documents", "method of organizing information", "innovative use of language"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["had a much narrower focus", "was less analytical", "was less biased", "emphasized results rather than causes"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["sought to extract lessons from the past", "sought to prove themselves superior", "sought to avoid their predecessor''s error", "sought to emphasize their nation''s greatness"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 5: The Brain as Predictor (過去問風) ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'The Brain as Predictor\n\nTraditional views of perception assumed that the brain passively receives sensory input and then processes it. According to a growing body of research, however, the brain can more accurately be described as __BLANK__. It constantly generates expectations based on past experience, current context, and learned associations. For example, you may feel your thirst quenched soon after drinking, even though the water has not yet been fully absorbed—your brain is predicting the outcome.\n\nNeurons fire in dynamic patterns that spread across regions. When you see something ambiguous—a shape that could be a branch or a snake—your brain settles on one interpretation, and that interpretation becomes your conscious experience. Remarkably, this can happen __BLANK__. If your brain concludes that the object is a snake, it may prepare your body to react before the visual cortex has finished processing the image. Anticipation and reaction can precede full perceptual confirmation.\n\nThe way the brain operates __BLANK__. Consider anxiety before public speaking: the brain may raise your heart rate and make your hands perspire before you have said a word. Yet the same predictive machinery can be trained. By reframing how we interpret bodily signals and situations, we can turn anxiety into focused energy. Research on such techniques suggests that understanding the brain''s predictive nature can help people build resilience and adapt more effectively to stress.',
  'The Brain as Predictor',
  E'The Brain as Predictor\n\nTraditional views of perception assumed that the brain passively receives sensory input and then processes it. According to a growing body of research, however, the brain can more accurately be described as __BLANK__. It constantly generates expectations based on past experience, current context, and learned associations. For example, you may feel your thirst quenched soon after drinking, even though the water has not yet been fully absorbed—your brain is predicting the outcome.\n\nNeurons fire in dynamic patterns that spread across regions. When you see something ambiguous—a shape that could be a branch or a snake—your brain settles on one interpretation, and that interpretation becomes your conscious experience. Remarkably, this can happen __BLANK__. If your brain concludes that the object is a snake, it may prepare your body to react before the visual cortex has finished processing the image. Anticipation and reaction can precede full perceptual confirmation.\n\nThe way the brain operates __BLANK__. Consider anxiety before public speaking: the brain may raise your heart rate and make your hands perspire before you have said a word. Yet the same predictive machinery can be trained. By reframing how we interpret bodily signals and situations, we can turn anxiety into focused energy. Research on such techniques suggests that understanding the brain''s predictive nature can help people build resilience and adapt more effectively to stress.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["a generator of predictions", "a supervisor in a busy office", "a translator for images", "a scanner and filter combination"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["before the sensory data is fully processed", "in multiple regions simultaneously", "more slowly than previously believed", "below the cellular level"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["can be used to our advantage", "is still not fully understood", "produces bizarre illusions", "makes it hard to control our emotions"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 6: Evolutionary Anachronisms (過去問風) ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'Evolutionary Anachronisms\n\nEarth''s ecosystems have been shaped by the rise and fall of large animals. Mammoths, mastodons, and other megafauna once played vital roles in dispersing seeds and shaping vegetation. Many were driven to extinction by a combination of climate change and human hunting. One tree species evolved large, tough fruits and sharp thorns, likely to attract large herbivores that could swallow the fruit whole and to deter smaller ones. Today, few animals find the fruit palatable, and the thorns serve little purpose. __BLANK__: the cause of megafauna extinction was not climate or hunting alone but a complex interplay of factors, and the tree''s traits are remnants of a lost world.\n\nThe tree''s range contracted after the megafauna disappeared. How it survived at all is a puzzle. One hypothesis is that humans who valued its wood for tools or weapons inadvertently spread its seeds. __BLANK__: the same species that may have contributed to megafauna decline later became essential to the survival of a plant that had depended on those animals. Human agency, often destructive, sometimes filled an ecological gap.\n\nBiologists call such species evolutionary anachronisms. It is tempting to assume the tree has __BLANK__—that in the millennia since the megafauna vanished, it should have adapted to new dispersers or shed its now-useless traits. Yet the tree can live for centuries, and a few thousand years is a short time in evolutionary terms. New adaptations on that scale often require millions of years. The tree persists not because it has failed to evolve but because it has endured.',
  'Evolutionary Anachronisms',
  E'Evolutionary Anachronisms\n\nEarth''s ecosystems have been shaped by the rise and fall of large animals. Mammoths, mastodons, and other megafauna once played vital roles in dispersing seeds and shaping vegetation. Many were driven to extinction by a combination of climate change and human hunting. One tree species evolved large, tough fruits and sharp thorns, likely to attract large herbivores that could swallow the fruit whole and to deter smaller ones. Today, few animals find the fruit palatable, and the thorns serve little purpose. __BLANK__: the cause of megafauna extinction was not climate or hunting alone but a complex interplay of factors, and the tree''s traits are remnants of a lost world.\n\nThe tree''s range contracted after the megafauna disappeared. How it survived at all is a puzzle. One hypothesis is that humans who valued its wood for tools or weapons inadvertently spread its seeds. __BLANK__: the same species that may have contributed to megafauna decline later became essential to the survival of a plant that had depended on those animals. Human agency, often destructive, sometimes filled an ecological gap.\n\nBiologists call such species evolutionary anachronisms. It is tempting to assume the tree has __BLANK__—that in the millennia since the megafauna vanished, it should have adapted to new dispersers or shed its now-useless traits. Yet the tree can live for centuries, and a few thousand years is a short time in evolutionary terms. New adaptations on that scale often require millions of years. The tree persists not because it has failed to evolve but because it has endured.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["Scientists suspect the cause was not as simple as that", "They left an observable legacy", "Their food sources also disappeared", "This could have been prevented"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["has an ironic aspect", "is now highly uncertain", "creates an even deeper mystery", "causes problems for some humans"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["failed to make new adaptations", "recently increased in number", "actually changed its ecosystem", "returned to an old behavior"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 7: The Origins of Writing ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'The Origins of Writing\n\nWriting systems emerged independently in several parts of the world: Mesopotamia, Egypt, China, and Mesoamerica. The earliest forms were often tied to accounting and administration rather than literature. Clay tablets from ancient Mesopotamia record quantities of grain, livestock, and labor. __BLANK__: writing was not initially a means of self-expression but a tool for managing complex economies and bureaucracies. Only later did it come to record myths, laws, and chronicles.\n\nScholars once assumed that writing spread from a single source. __BLANK__. The structures of Chinese characters, Egyptian hieroglyphs, and Mayan glyphs are too different to have sprung from one origin. Each system reflects the language and needs of the society that developed it. The invention of writing was a cognitive and social breakthrough that occurred multiple times in human history.\n\n__BLANK__. Societies with writing could preserve knowledge across generations, coordinate large populations, and develop more elaborate legal and religious traditions. The transition from oral to written culture did not simply add a new technology; it altered how people thought about memory, authority, and the past. The consequences of that transition are still with us today.',
  'The Origins of Writing',
  E'The Origins of Writing\n\nWriting systems emerged independently in several parts of the world: Mesopotamia, Egypt, China, and Mesoamerica. The earliest forms were often tied to accounting and administration rather than literature. Clay tablets from ancient Mesopotamia record quantities of grain, livestock, and labor. __BLANK__: writing was not initially a means of self-expression but a tool for managing complex economies and bureaucracies. Only later did it come to record myths, laws, and chronicles.\n\nScholars once assumed that writing spread from a single source. __BLANK__. The structures of Chinese characters, Egyptian hieroglyphs, and Mayan glyphs are too different to have sprung from one origin. Each system reflects the language and needs of the society that developed it. The invention of writing was a cognitive and social breakthrough that occurred multiple times in human history.\n\n__BLANK__. Societies with writing could preserve knowledge across generations, coordinate large populations, and develop more elaborate legal and religious traditions. The transition from oral to written culture did not simply add a new technology; it altered how people thought about memory, authority, and the past. The consequences of that transition are still with us today.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["This suggests a practical origin", "This was later disproved", "This limited its spread", "This made it exclusive"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["That view is no longer tenable", "That view has been confirmed", "That view inspired new research", "That view applied only to Egypt"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["The impact of writing was profound", "The impact of writing was delayed", "The impact of writing was contested", "The impact of writing was limited"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 8: Climate and Civilization ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'Climate and Civilization\n\nHistorians have long debated the role of climate in the collapse of ancient societies. Drought, crop failure, and resource scarcity are often cited as factors in the decline of once-powerful states. __BLANK__: climate alone rarely explains collapse. Political instability, conflict, overexpansion, and social inequality typically interacted with environmental stress. A society that had depleted its soils or overexploited its forests was more vulnerable when drought or cooling arrived.\n\nPaleoclimatologists use ice cores, tree rings, and sediment layers to reconstruct past climates. These records show that some periods of upheaval coincided with sharp shifts in temperature or rainfall. __BLANK__: did climate change cause the collapse, or did it merely accelerate processes already underway? In many cases, the answer is both. Environmental change exposed weaknesses that might otherwise have been managed or postponed.\n\n__BLANK__. Today we face not only natural variability but human-induced warming, and the same questions apply: how resilient are our institutions, and how quickly can we adapt? The lessons of the past do not offer simple parallels, but they remind us that civilizations have always existed in dialogue with the climate, and that the margin between stability and crisis can be narrow.',
  'Climate and Civilization',
  E'Climate and Civilization\n\nHistorians have long debated the role of climate in the collapse of ancient societies. Drought, crop failure, and resource scarcity are often cited as factors in the decline of once-powerful states. __BLANK__: climate alone rarely explains collapse. Political instability, conflict, overexpansion, and social inequality typically interacted with environmental stress. A society that had depleted its soils or overexploited its forests was more vulnerable when drought or cooling arrived.\n\nPaleoclimatologists use ice cores, tree rings, and sediment layers to reconstruct past climates. These records show that some periods of upheaval coincided with sharp shifts in temperature or rainfall. __BLANK__: did climate change cause the collapse, or did it merely accelerate processes already underway? In many cases, the answer is both. Environmental change exposed weaknesses that might otherwise have been managed or postponed.\n\n__BLANK__. Today we face not only natural variability but human-induced warming, and the same questions apply: how resilient are our institutions, and how quickly can we adapt? The lessons of the past do not offer simple parallels, but they remind us that civilizations have always existed in dialogue with the climate, and that the margin between stability and crisis can be narrow.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["Most scholars now agree", "Few scholars have questioned", "Some scholars insist", "Historians have proven"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["The difficulty lies in establishing causation", "The evidence is overwhelmingly clear", "The method has been abandoned", "The records are too sparse"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["These questions have renewed relevance", "These questions have been settled", "These questions were unique to the past", "These questions lack scientific basis"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 9: The Placebo Effect ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'The Placebo Effect\n\nWhen patients in clinical trials receive an inactive substance—a sugar pill or saline injection—they sometimes improve anyway. This phenomenon is known as the placebo effect. For decades it was dismissed as "all in the mind" or as a nuisance that had to be controlled for in drug trials. __BLANK__: the placebo effect is a real physiological response. Brain imaging has shown that placebos can trigger the release of endorphins and activate regions involved in pain relief and expectation. The mind can influence the body in measurable ways.\n\nThe strength of the effect varies. It tends to be larger when the treatment involves a ritual—injections often produce a stronger placebo response than pills—and when the patient trusts the clinician. __BLANK__: the context of care, not just the chemical content of a drug, shapes outcomes. This has ethical implications. Should doctors harness placebos deliberately? Most agree that deception is wrong, but some argue that open-label placebos—where patients are told they are receiving an inactive treatment—can still reduce symptoms in certain conditions.\n\n__BLANK__. Understanding how expectation and context affect health could lead to better trial design, more honest communication with patients, and perhaps ways to enhance the benefits of genuine treatments by optimizing the circumstances in which they are given.',
  'The Placebo Effect',
  E'The Placebo Effect\n\nWhen patients in clinical trials receive an inactive substance—a sugar pill or saline injection—they sometimes improve anyway. This phenomenon is known as the placebo effect. For decades it was dismissed as "all in the mind" or as a nuisance that had to be controlled for in drug trials. __BLANK__: the placebo effect is a real physiological response. Brain imaging has shown that placebos can trigger the release of endorphins and activate regions involved in pain relief and expectation. The mind can influence the body in measurable ways.\n\nThe strength of the effect varies. It tends to be larger when the treatment involves a ritual—injections often produce a stronger placebo response than pills—and when the patient trusts the clinician. __BLANK__: the context of care, not just the chemical content of a drug, shapes outcomes. This has ethical implications. Should doctors harness placebos deliberately? Most agree that deception is wrong, but some argue that open-label placebos—where patients are told they are receiving an inactive treatment—can still reduce symptoms in certain conditions.\n\n__BLANK__. Understanding how expectation and context affect health could lead to better trial design, more honest communication with patients, and perhaps ways to enhance the benefits of genuine treatments by optimizing the circumstances in which they are given.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["Research has overturned that view", "Research has confirmed that view", "Research has ignored that view", "Research has complicated that view"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["The implication is that", "The implication is instead", "The implication has been rejected", "The implication remains unclear"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["The study of placebos is gaining respect", "The study of placebos has been abandoned", "The study of placebos is purely theoretical", "The study of placebos has no practical use"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 10: The Nature of Genius ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'The Nature of Genius\n\nGenius has been attributed to divine inspiration, exceptional genes, or simply countless hours of practice. Modern research suggests that __BLANK__. High achievement in fields from music to mathematics usually requires both innate aptitude and deliberate practice over many years. Prodigies exist, but most experts in any domain have accumulated thousands of hours of focused effort. The "ten-year rule"—that it takes at least a decade to master a complex skill—has been observed across disciplines.\n\nCreativity often involves making connections between seemingly unrelated ideas. Some of the most celebrated innovations arose when someone applied a concept from one field to another. __BLANK__: breakthroughs are not random but often occur when a prepared mind encounters the right problem in the right context. Chance favors the prepared mind, as the saying goes.\n\n__BLANK__. Cultures that value innovation tend to reward risk-taking and tolerate failure. Educational systems that encourage curiosity and interdisciplinary thinking may produce more people who can combine ideas in novel ways. The myth of the lone genius obscures the social and institutional factors that enable exceptional achievement. Genius may be rare, but the conditions that nurture it can be cultivated.',
  'The Nature of Genius',
  E'The Nature of Genius\n\nGenius has been attributed to divine inspiration, exceptional genes, or simply countless hours of practice. Modern research suggests that __BLANK__. High achievement in fields from music to mathematics usually requires both innate aptitude and deliberate practice over many years. Prodigies exist, but most experts in any domain have accumulated thousands of hours of focused effort. The "ten-year rule"—that it takes at least a decade to master a complex skill—has been observed across disciplines.\n\nCreativity often involves making connections between seemingly unrelated ideas. Some of the most celebrated innovations arose when someone applied a concept from one field to another. __BLANK__: breakthroughs are not random but often occur when a prepared mind encounters the right problem in the right context. Chance favors the prepared mind, as the saying goes.\n\n__BLANK__. Cultures that value innovation tend to reward risk-taking and tolerate failure. Educational systems that encourage curiosity and interdisciplinary thinking may produce more people who can combine ideas in novel ways. The myth of the lone genius obscures the social and institutional factors that enable exceptional achievement. Genius may be rare, but the conditions that nurture it can be cultivated.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["the reality is more nuanced", "the reality is purely genetic", "the reality defies explanation", "the reality has been exaggerated"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["Studies support a familiar idea", "Studies support a radical idea", "Studies have disproven this", "Studies remain inconclusive"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["Environment and culture also matter", "Environment and culture are irrelevant", "Environment and culture are immutable", "Environment and culture are overemphasized"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 11: Democracy and Dissent ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'Democracy and Dissent\n\nDemocratic theory holds that citizens should be able to criticize their government without fear of reprisal. Freedom of speech and assembly are not merely individual rights but prerequisites for collective decision-making. __BLANK__: a democracy that cannot tolerate dissent risks becoming an echo chamber, where flawed policies go unchallenged and minority views are silenced. History is replete with examples of governments that claimed to speak for the people while suppressing those who disagreed.\n\nYet all democracies place some limits on expression. Defamation, incitement to violence, and the spread of harmful falsehoods are often restricted. __BLANK__: where should the line be drawn between protected speech and speech that undermines the very conditions necessary for democratic debate? Different societies answer this question differently, and the answer can shift in times of crisis or polarization.\n\n__BLANK__. When trust in institutions erodes, people may turn to alternative sources of information, some of which spread conspiracy theories or demonize opponents. A healthy democracy depends not only on legal protections for speech but on a culture that values evidence, tolerates disagreement, and distinguishes between criticism and disinformation. Without that culture, the right to dissent can be weaponized against democracy itself.',
  'Democracy and Dissent',
  E'Democracy and Dissent\n\nDemocratic theory holds that citizens should be able to criticize their government without fear of reprisal. Freedom of speech and assembly are not merely individual rights but prerequisites for collective decision-making. __BLANK__: a democracy that cannot tolerate dissent risks becoming an echo chamber, where flawed policies go unchallenged and minority views are silenced. History is replete with examples of governments that claimed to speak for the people while suppressing those who disagreed.\n\nYet all democracies place some limits on expression. Defamation, incitement to violence, and the spread of harmful falsehoods are often restricted. __BLANK__: where should the line be drawn between protected speech and speech that undermines the very conditions necessary for democratic debate? Different societies answer this question differently, and the answer can shift in times of crisis or polarization.\n\n__BLANK__. When trust in institutions erodes, people may turn to alternative sources of information, some of which spread conspiracy theories or demonize opponents. A healthy democracy depends not only on legal protections for speech but on a culture that values evidence, tolerates disagreement, and distinguishes between criticism and disinformation. Without that culture, the right to dissent can be weaponized against democracy itself.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["The reasoning is straightforward", "The reasoning is controversial", "The reasoning has been abandoned", "The reasoning is purely historical"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["The enduring dilemma is", "The enduring dilemma was resolved", "The enduring dilemma is irrelevant", "The enduring dilemma is theoretical"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["The digital age has complicated this balance", "The digital age has simplified this balance", "The digital age has made dissent obsolete", "The digital age has eliminated the need for debate"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 12: Language and Thought ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'Language and Thought\n\nThe question of whether language shapes thought has fascinated philosophers and linguists for centuries. Some argued that we can only think what we can say—that language is the medium of thought. Others insisted that thought is independent of language and that we often struggle to put our ideas into words. __BLANK__: speakers of languages that lack distinct words for certain colors can still perceive color differences, but they may categorize and remember colors differently from speakers of languages with richer color vocabularies. Language does not determine perception, but it can influence how we attend to and encode experience.\n\nResearchers have studied speakers of languages that use cardinal directions (north, south) instead of relative terms (left, right) for spatial description. Such speakers maintain a constant sense of orientation and perform better on some spatial tasks. __BLANK__: the structure of a language can encourage habits of attention and cognition that persist even when one is not speaking. This does not mean that thought is a prisoner of language, but that language is one of the tools with which we construct our mental world.\n\n__BLANK__. Bilinguals sometimes report that they feel like different people in different languages, or that certain emotions are easier to express in one language than another. Such reports are subjective, but they hint at the ways in which language is bound up with identity, memory, and emotion—not just with cold cognition.',
  'Language and Thought',
  E'Language and Thought\n\nThe question of whether language shapes thought has fascinated philosophers and linguists for centuries. Some argued that we can only think what we can say—that language is the medium of thought. Others insisted that thought is independent of language and that we often struggle to put our ideas into words. __BLANK__: speakers of languages that lack distinct words for certain colors can still perceive color differences, but they may categorize and remember colors differently from speakers of languages with richer color vocabularies. Language does not determine perception, but it can influence how we attend to and encode experience.\n\nResearchers have studied speakers of languages that use cardinal directions (north, south) instead of relative terms (left, right) for spatial description. Such speakers maintain a constant sense of orientation and perform better on some spatial tasks. __BLANK__: the structure of a language can encourage habits of attention and cognition that persist even when one is not speaking. This does not mean that thought is a prisoner of language, but that language is one of the tools with which we construct our mental world.\n\n__BLANK__. Bilinguals sometimes report that they feel like different people in different languages, or that certain emotions are easier to express in one language than another. Such reports are subjective, but they hint at the ways in which language is bound up with identity, memory, and emotion—not just with cold cognition.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["Evidence from color perception is suggestive", "Evidence from color perception is conclusive", "Evidence from color perception has been dismissed", "Evidence from color perception is irrelevant"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["The implication is that", "The implication has been refuted", "The implication applies only to navigation", "The implication is trivial"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["The relationship may extend beyond cognition", "The relationship is purely cognitive", "The relationship has been disproven", "The relationship is unique to bilinguals"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 13: The Cost of Economic Growth ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'The Cost of Economic Growth\n\nFor much of the twentieth century, economic growth was seen as an unqualified good. Rising GDP meant more jobs, higher incomes, and better living standards. Since the 1970s, however, economists and environmentalists have questioned whether growth can continue indefinitely on a finite planet. __BLANK__: the depletion of natural resources, pollution, and climate change are often treated as "externalities" in conventional economics—costs not reflected in market prices. As a result, growth can be overstated and its true cost underestimated.\n\nSome have called for "degrowth" or a shift to well-being indicators that go beyond GDP. Others argue that innovation and green technology can decouple growth from environmental damage. __BLANK__: the evidence is mixed. Some countries have reduced carbon emissions while growing their economies, but global material use and emissions have continued to rise. Efficiency gains have often been offset by increased consumption.\n\n__BLANK__. The question is not only whether growth is sustainable but who benefits from it and who bears its costs. Inequality within and between nations has grown in many places, and the benefits of growth have not always reached the poorest. A rethinking of progress may require not only new metrics but new policies that distribute the gains—and share the burdens—more fairly.',
  'The Cost of Economic Growth',
  E'The Cost of Economic Growth\n\nFor much of the twentieth century, economic growth was seen as an unqualified good. Rising GDP meant more jobs, higher incomes, and better living standards. Since the 1970s, however, economists and environmentalists have questioned whether growth can continue indefinitely on a finite planet. __BLANK__: the depletion of natural resources, pollution, and climate change are often treated as "externalities" in conventional economics—costs not reflected in market prices. As a result, growth can be overstated and its true cost underestimated.\n\nSome have called for "degrowth" or a shift to well-being indicators that go beyond GDP. Others argue that innovation and green technology can decouple growth from environmental damage. __BLANK__: the evidence is mixed. Some countries have reduced carbon emissions while growing their economies, but global material use and emissions have continued to rise. Efficiency gains have often been offset by increased consumption.\n\n__BLANK__. The question is not only whether growth is sustainable but who benefits from it and who bears its costs. Inequality within and between nations has grown in many places, and the benefits of growth have not always reached the poorest. A rethinking of progress may require not only new metrics but new policies that distribute the gains—and share the burdens—more fairly.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["A central criticism is that", "A central criticism was rejected", "A central criticism is outdated", "A central criticism is irrelevant"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["Whether decoupling is possible remains disputed", "Decoupling has been achieved globally", "Decoupling is theoretically impossible", "Decoupling is no longer a goal"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["Distribution is equally crucial", "Distribution has been solved", "Distribution is a separate issue", "Distribution is irrelevant to growth"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 14: The Evolution of Cooperation ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'The Evolution of Cooperation\n\nWhy do humans cooperate with strangers, sometimes at great cost to themselves? Evolutionary theory has long emphasized competition and survival of the fittest. Yet cooperation is widespread in nature and in human societies. __BLANK__: under the right conditions, cooperative behavior can be favored by natural selection. If individuals interact repeatedly and can recognize one another, strategies that reward cooperation and punish defection can thrive. Tit-for-tat and similar rules can emerge and persist.\n\nHuman cooperation extends beyond kin and small groups. We pay taxes, follow rules, and contribute to public goods even when we could free-ride. __BLANK__: norms, reputation, and institutions allow cooperation to scale. Societies that develop ways to enforce norms and punish cheaters can sustain larger and more complex forms of collective action. Culture and institutions thus become part of the story of how cooperation evolved.\n\n__BLANK__. Climate change, pandemics, and nuclear proliferation require coordination at a global scale. The same mechanisms that enabled cooperation within groups—reciprocity, reputation, punishment—may be insufficient when the group is all of humanity and the stakes are existential. Understanding the evolution of cooperation may be essential to designing institutions that can meet twenty-first-century challenges.',
  'The Evolution of Cooperation',
  E'The Evolution of Cooperation\n\nWhy do humans cooperate with strangers, sometimes at great cost to themselves? Evolutionary theory has long emphasized competition and survival of the fittest. Yet cooperation is widespread in nature and in human societies. __BLANK__: under the right conditions, cooperative behavior can be favored by natural selection. If individuals interact repeatedly and can recognize one another, strategies that reward cooperation and punish defection can thrive. Tit-for-tat and similar rules can emerge and persist.\n\nHuman cooperation extends beyond kin and small groups. We pay taxes, follow rules, and contribute to public goods even when we could free-ride. __BLANK__: norms, reputation, and institutions allow cooperation to scale. Societies that develop ways to enforce norms and punish cheaters can sustain larger and more complex forms of collective action. Culture and institutions thus become part of the story of how cooperation evolved.\n\n__BLANK__. Climate change, pandemics, and nuclear proliferation require coordination at a global scale. The same mechanisms that enabled cooperation within groups—reciprocity, reputation, punishment—may be insufficient when the group is all of humanity and the stakes are existential. Understanding the evolution of cooperation may be essential to designing institutions that can meet twenty-first-century challenges.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["Game theory and experiments suggest", "Game theory and experiments have disproven", "Game theory and experiments are irrelevant", "Game theory and experiments are inconclusive"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["One answer is that", "One answer has been rejected", "One answer is that genetics alone explains it", "One answer is that cooperation is irrational"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["These insights have urgent applications", "These insights are purely theoretical", "These insights have been refuted", "These insights apply only to the past"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 15: The Rise of Cities ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'The Rise of Cities\n\nFor most of human history, the majority of people lived in rural areas. The shift to an urban majority is recent and accelerating. Cities concentrate people, capital, and innovation; they generate a disproportionate share of economic output and cultural production. __BLANK__: cities also concentrate poverty, pollution, and vulnerability to disease. The same density that enables creativity and exchange can also amplify inequality and risk. Urbanization is not uniformly beneficial.\n\nHistorians trace the first cities to the emergence of agriculture and surplus production. Once some people could be freed from farming, they could specialize in crafts, trade, administration, or religion. __BLANK__: cities have always been nodes of power, but also of diversity and dissent. They attract migrants, mix cultures, and sometimes challenge the authority of rulers. The city has been both the seat of empire and the cradle of revolution.\n\n__BLANK__. Climate change will test urban infrastructure: heat waves, floods, and rising seas threaten coastal megacities. Pandemics spread quickly in dense populations. The future of humanity is urban, and the quality of that future will depend on how we design cities—for resilience, equity, and sustainability—in the decades to come.',
  'The Rise of Cities',
  E'The Rise of Cities\n\nFor most of human history, the majority of people lived in rural areas. The shift to an urban majority is recent and accelerating. Cities concentrate people, capital, and innovation; they generate a disproportionate share of economic output and cultural production. __BLANK__: cities also concentrate poverty, pollution, and vulnerability to disease. The same density that enables creativity and exchange can also amplify inequality and risk. Urbanization is not uniformly beneficial.\n\nHistorians trace the first cities to the emergence of agriculture and surplus production. Once some people could be freed from farming, they could specialize in crafts, trade, administration, or religion. __BLANK__: cities have always been nodes of power, but also of diversity and dissent. They attract migrants, mix cultures, and sometimes challenge the authority of rulers. The city has been both the seat of empire and the cradle of revolution.\n\n__BLANK__. Climate change will test urban infrastructure: heat waves, floods, and rising seas threaten coastal megacities. Pandemics spread quickly in dense populations. The future of humanity is urban, and the quality of that future will depend on how we design cities—for resilience, equity, and sustainability—in the decades to come.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["Yet the picture is ambiguous", "Yet the picture is rosy", "Yet the picture is unchanged", "Yet the picture is irrelevant"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["The paradox is an old one", "The paradox has been resolved", "The paradox is unique to modern cities", "The paradox is purely economic"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["Twenty-first-century cities face new pressures", "Twenty-first-century cities have solved old problems", "Twenty-first-century cities are in decline", "Twenty-first-century cities are unchanged"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 16: Art and Censorship ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'Art and Censorship\n\nGovernments and institutions have long sought to control what art is made, displayed, or performed. The reasons given are often moral or political: to protect the public from offensive content, to uphold religious or ideological orthodoxy, or to maintain social order. __BLANK__: censorship can also suppress dissent, silence minority voices, and stifle the experimentation that has produced many of the works we now consider masterpieces. The same power that can shield audiences can be used to enforce conformity.\n\nArtists have responded in various ways. Some have complied, some have gone into exile, and some have found ways to encode subversive messages in allegory or abstraction. __BLANK__: what one era condemns as obscene or blasphemous, another may celebrate as bold or prophetic. The history of art is in part a history of boundaries being tested and redrawn. Today''s controversies over representation, appropriation, and offense echo earlier debates, even if the terms have changed.\n\n__BLANK__. In liberal democracies, legal protections for artistic expression are strong but not absolute; obscenity, incitement, and in some places hate speech may be restricted. The harder questions often concern not the law but social pressure: when does criticism become censorship, and when does the artist''s freedom conflict with the dignity or safety of others? There are no easy answers, but the conversation itself is a sign of a society that takes both art and accountability seriously.',
  'Art and Censorship',
  E'Art and Censorship\n\nGovernments and institutions have long sought to control what art is made, displayed, or performed. The reasons given are often moral or political: to protect the public from offensive content, to uphold religious or ideological orthodoxy, or to maintain social order. __BLANK__: censorship can also suppress dissent, silence minority voices, and stifle the experimentation that has produced many of the works we now consider masterpieces. The same power that can shield audiences can be used to enforce conformity.\n\nArtists have responded in various ways. Some have complied, some have gone into exile, and some have found ways to encode subversive messages in allegory or abstraction. __BLANK__: what one era condemns as obscene or blasphemous, another may celebrate as bold or prophetic. The history of art is in part a history of boundaries being tested and redrawn. Today''s controversies over representation, appropriation, and offense echo earlier debates, even if the terms have changed.\n\n__BLANK__. In liberal democracies, legal protections for artistic expression are strong but not absolute; obscenity, incitement, and in some places hate speech may be restricted. The harder questions often concern not the law but social pressure: when does criticism become censorship, and when does the artist''s freedom conflict with the dignity or safety of others? There are no easy answers, but the conversation itself is a sign of a society that takes both art and accountability seriously.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["Critics of censorship point out that", "Critics of censorship have been silenced", "Critics of censorship are rare", "Critics of censorship focus only on law"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["History reminds us that standards shift", "History reminds us that censorship always fails", "History reminds us that art is universal", "History reminds us that offense is objective"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["The legal landscape is only part of the story", "The legal landscape is the only relevant factor", "The legal landscape has been settled", "The legal landscape is identical everywhere"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;

-- ========== 17: The Limits of Memory ==========
INSERT INTO public.reading_passages (level, genre, passage_type, body, title, content)
VALUES (
  '1級', 'expository', 'long_fill',
  E'The Limits of Memory\n\nMemory is not a perfect recording of the past. Decades of research have shown that we reconstruct rather than replay our experiences. Each time we recall an event, we may subtly alter it; over time, memories can drift, merge, or be contaminated by suggestion. __BLANK__: eyewitness testimony, once considered among the most reliable forms of evidence, is now treated with caution in courts. Innocent people have been convicted on the basis of confident but false memories.\n\nYet memory is also adaptive. We do not need to store every detail of every moment; we extract gist, meaning, and lessons. Forgetting can be functional—it clears space and allows us to generalize. __BLANK__: the same flexibility that allows us to learn and adapt also makes us vulnerable to distortion. The line between healthy reconstruction and harmful false memory is not always clear, especially in cases of trauma or when memories are recovered after long periods.\n\n__BLANK__. Technologies that could enhance or implant memories raise ethical questions: who should have access, and for what purposes? The prospect of editing or erasing memories—once the stuff of science fiction—is now a subject of serious research. As the science advances, society will need to decide how much we value memory as a record of the past versus as a resource we might one day be able to modify.',
  'The Limits of Memory',
  E'The Limits of Memory\n\nMemory is not a perfect recording of the past. Decades of research have shown that we reconstruct rather than replay our experiences. Each time we recall an event, we may subtly alter it; over time, memories can drift, merge, or be contaminated by suggestion. __BLANK__: eyewitness testimony, once considered among the most reliable forms of evidence, is now treated with caution in courts. Innocent people have been convicted on the basis of confident but false memories.\n\nYet memory is also adaptive. We do not need to store every detail of every moment; we extract gist, meaning, and lessons. Forgetting can be functional—it clears space and allows us to generalize. __BLANK__: the same flexibility that allows us to learn and adapt also makes us vulnerable to distortion. The line between healthy reconstruction and harmful false memory is not always clear, especially in cases of trauma or when memories are recovered after long periods.\n\n__BLANK__. Technologies that could enhance or implant memories raise ethical questions: who should have access, and for what purposes? The prospect of editing or erasing memories—once the stuff of science fiction—is now a subject of serious research. As the science advances, society will need to decide how much we value memory as a record of the past versus as a resource we might one day be able to modify.'
);
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 0, '["The implications for the legal system are significant", "The implications for the legal system are negligible", "The implications for the legal system have been resolved", "The implications for the legal system are purely theoretical"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 1, '["The paradox is that", "The paradox has been solved", "The paradox is unique to trauma", "The paradox is irrelevant to courts"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
INSERT INTO public.reading_passage_blanks (passage_id, blank_index, choices, correct_index)
SELECT id, 2, '["The future may bring even harder choices", "The future will resolve these questions", "The future is irrelevant to memory research", "The future will eliminate false memory"]', 0
FROM public.reading_passages WHERE level = '1級' AND passage_type = 'long_fill' ORDER BY id DESC LIMIT 1;
